//! HTML report generation.

use std::path::Path;

use anyhow::Result;
use skill_doctor_core::models::{ScanResult, Severity};

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

/// Generate an HTML report file from scan results.
pub fn generate_html(result: &ScanResult, output_path: &Path) -> Result<()> {
    let severity_color = |s: &Severity| -> &str {
        match s {
            Severity::Critical => "#dc2626",
            Severity::High => "#ea580c",
            Severity::Medium => "#ca8a04",
            Severity::Low => "#2563eb",
            Severity::Info => "#6b7280",
        }
    };

    let findings_html: String = result
        .findings
        .iter()
        .map(|f| {
            format!(
                r#"<div class="finding">
                    <span class="severity" style="background:{}; color:white; padding:2px 8px; border-radius:4px; font-weight:bold;">{}</span>
                    <strong>{}</strong><br/>
                    <span class="file">📄 {}{}</span><br/>
                    <p>{}</p>
                    <p class="remediation">💡 {}</p>
                    <small>Engine: {} | Confidence: {:.0}%</small>
                </div>"#,
                severity_color(&f.severity),
                escape_html(&f.severity.to_string()),
                escape_html(&f.category),
                escape_html(&f.file),
                f.line.map(|l| format!(":{}", l)).unwrap_or_default(),
                escape_html(&f.description),
                escape_html(&f.remediation),
                escape_html(&f.engine.to_string()),
                f.confidence * 100.0,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Skill Doctor Report — {scan_id}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
        .container {{ max-width: 800px; margin: 0 auto; }}
        h1 {{ color: #f8fafc; margin-bottom: 0.5rem; }}
        .meta {{ color: #94a3b8; margin-bottom: 2rem; }}
        .summary {{ background: #1e293b; padding: 1.5rem; border-radius: 12px; margin-bottom: 2rem; }}
        .risk {{ font-size: 1.5rem; font-weight: bold; }}
        .risk.DANGEROUS {{ color: #dc2626; }}
        .risk.CAUTION {{ color: #ea580c; }}
        .risk.SAFE {{ color: #22c55e; }}
        .finding {{ background: #1e293b; padding: 1rem; border-radius: 8px; margin-bottom: 1rem; border-left: 4px solid #334155; }}
        .finding .file {{ color: #94a3b8; font-family: monospace; }}
        .finding .remediation {{ color: #22d3ee; font-style: italic; }}
        small {{ color: #64748b; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🩺 Skill Doctor Report</h1>
        <p class="meta">Scan ID: {scan_id} | {scanned_at} | Duration: {duration}s</p>

        <div class="summary">
            <p class="risk {risk_level}">{risk_level} — {risk_score:.1}/10.0</p>
            <p>{findings_count} findings | Layers: {layers}</p>
        </div>

        {findings_html}

        <p style="text-align:center; color:#475569; margin-top:2rem;">
            Generated by <strong>Skill Doctor v{version}</strong> · Kalaris Labs
        </p>
    </div>
</body>
</html>"#,
        scan_id = &result.scan_id[..8],
        scanned_at = result.scanned_at.format("%Y-%m-%d %H:%M:%S UTC"),
        duration = result.duration_ms as f64 / 1000.0,
        risk_level = result.risk_level,
        risk_score = result.risk_score,
        findings_count = result.findings.len(),
        layers = result.layers_run.join(", "),
        findings_html = findings_html,
        version = env!("CARGO_PKG_VERSION"),
    );

    std::fs::write(output_path, html)?;
    Ok(())
}
